name: Android CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  telegram:
    name: Notify telegram group
    runs-on: ubuntu-latest
    steps:
      - name: Notify the commit on Telegram
        uses: EverythingSuckz/github-telegram-notify@main
        with:
          bot_token: '${{ secrets.BOT_TOKEN }}'
          chat_id: '${{ secrets.CHAT_ID }}'
          topic_id: '${{ secrets.TOPIC_ID }}'
  build:
    name: Build APKs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [debug, release]
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Give permission to executable
        run: chmod +x gradlew

      - name: Generate APK
        run: ./gradlew assemble${{ matrix.build-type }}

      - name: Upload APK
        uses: actions/upload-artifact@master
        with:
          name: app-${{ matrix.build-type }}
          path: app/build/outputs/apk/${{ matrix.build-type }}/app-${{ matrix.build-type }}.apk
