name: Android CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - assets/**
      - README.md
      - LICENSE
      - .gitignore

jobs:
  buildDebug:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          
      - name: Allow gradlew permission
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug
          
      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with:
          name: app-devug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload debug output metadata
        uses: actions/upload-artifact@v3
        with:
          name: output-metadata-debug
          path: app/build/outputs/apk/debug/output-metadata.json

  buildRelease:
    name: Build Release APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          
      - name: Allow gradlew permission
        run: chmod +x ./gradlew

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Upload release APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload release output metadata
        uses: actions/upload-artifact@v3
        with:
          name: output-metadata-release
          path: app/build/outputs/apk/release/output-metadata.json
