name: Release Build CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Give permission to executable
        run: chmod +x gradlew

      - name: Build with gradle
        uses: gradle/gradle-build-action@v2.9.0
        with:
          gradle-version: nightly
          arguments: assembleRelease

      - name: Upload release apks
        uses: actions/upload-artifact@v3
        with:
          path: app/build/outputs/apk/release/app-release.apk

